name = "aijobpath"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-kv-namespace-preview-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-namespace-id"
preview_id = "your-sessions-namespace-preview-id"

[analytics_engine_datasets]
binding = "ANALYTICS"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"