export const LEARNING_STYLES = [
  { value: 'visual', label: 'Visual (diagrams, charts, videos)' },
  { value: 'hands-on', label: 'Hands-on (projects, practice)' },
  { value: 'theoretical', label: 'Theoretical (reading, lectures)' },
  { value: 'collaborative', label: 'Collaborative (group work, discussions)' },
  { value: 'self-paced', label: 'Self-paced (independent study)' }
];

export const MAJORS = [
  // Technology & Computer Science
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Data Science",
  "Cybersecurity",
  "Information Systems",
  "Computer Engineering",
  "Artificial Intelligence",
  "Machine Learning",
  "Web Development",
  "Game Development",

  // Engineering
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Industrial Engineering",
  "Environmental Engineering",
  "Materials Engineering",
  "Petroleum Engineering",

  // Business & Economics
  "Business Administration",
  "Finance",
  "Economics",
  "Accounting",
  "Marketing",
  "International Business",
  "Entrepreneurship",
  "Supply Chain Management",
  "Human Resources",
  "Operations Management",

  // Science & Mathematics
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biochemistry",
  "Environmental Science",
  "Geology",
  "Astronomy",
  "Applied Mathematics",

  // Health & Medicine
  "Pre-Medicine",
  "Nursing",
  "Public Health",
  "Health Administration",
  "Pharmacy",
  "Physical Therapy",
  "Occupational Therapy",
  "Nutrition",
  "Medical Technology",
  "Biomedical Sciences",

  // Liberal Arts & Humanities
  "English",
  "Literature",
  "History",
  "Philosophy",
  "Political Science",
  "International Relations",
  "Sociology",
  "Anthropology",
  "Religious Studies",
  "Foreign Languages",

  // Communication & Media
  "Communications",
  "Journalism",
  "Public Relations",
  "Media Studies",
  "Broadcasting",
  "Digital Media",
  "Film Studies",
  "Advertising",

  // Creative Arts & Design
  "Graphic Design",
  "Art",
  "Fine Arts",
  "Interior Design",
  "Fashion Design",
  "Architecture",
  "Music",
  "Theater",
  "Creative Writing",
  "Photography",

  // Education
  "Education",
  "Elementary Education",
  "Secondary Education",
  "Special Education",
  "Educational Psychology",
  "Curriculum and Instruction",

  // Social Sciences
  "Psychology",
  "Criminal Justice",
  "Social Work",
  "Urban Planning",
  "Geography",
  "Public Administration",
  "Law Enforcement",

  // Agriculture & Natural Resources
  "Agriculture",
  "Agricultural Business",
  "Forestry",
  "Natural Resources",
  "Animal Science",
  "Plant Science",

  // Other Professional Fields
  "Law",
  "Pre-Law",
  "Library Science",
  "Sports Management",
  "Hospitality Management",
  "Tourism",
  "Recreation",
  "Undeclared",
  "Other"
]

export const UNIVERSITIES = [
  // United States (original list plus additions)
  "Stanford University",
  "Massachusetts Institute of Technology",
  "Harvard University",
  "University of California, Berkeley",
  "Carnegie Mellon University",
  "University of Washington",
  "Georgia Institute of Technology",
  "University of Illinois",
  "University of Texas at Austin",
  "University of Michigan",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "Cornell University",
  "California Institute of Technology",
  "University of California, Los Angeles",
  "University of Southern California",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "New York University",
  "University of Wisconsin-Madison",
  "University of California, San Diego",
  "University of North Carolina at Chapel Hill",
  "Boston University",
  "Purdue University",
  "Ohio State University",
  "University of Florida",
  "University of Maryland",
  "Arizona State University",
  "University of Virginia",
  "Penn State University",
  "University of Minnesota",
  "University of Colorado Boulder",
  "University of California, Irvine",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "Northeastern University",
  "University of Arizona",
  "Michigan State University",
  "University of Pittsburgh",
  "Indiana University",
  "University of Oregon",
  "University of Utah",
  "Texas A&M University",
  "Iowa State University",
  "University of Iowa",
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "Virginia Tech",
  "North Carolina State University",
  "University of Tennessee",
  "University of South Carolina",
  "University of Alabama",
  "University of Kentucky",
  "University of Missouri",
  "University of Kansas",
  "University of Nebraska",
  "University of Oklahoma",
  "Louisiana State University",
  "University of Arkansas",
  "University of Mississippi",
  "University of New Mexico",
  "University of Nevada, Las Vegas",
  "University of Hawaii",
  "University of Alaska",
  // US Additions
  "Temple University",
  "Florida State University",
  "George Washington University",
  "University at Buffalo (SUNY)",
  "San Diego State University",
  "Clemson University",
  "University of Vermont",
  "Kansas State University",
  "Oregon State University",

  // United Kingdom (top universities)
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "King’s College London",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "London School of Economics and Political Science (LSE)",
  "University of Warwick",
  "University of Glasgow",
  "Durham University",
  "Cardiff University",
  // UK Additions
  "University of York",
  "University of Leeds",
  "University of Exeter",
  "Queen Mary University of London",
  "University of Aberdeen",
  "University of Leicester",

  // Canada
  "University of Toronto",
  "University of British Columbia",
  "McGill University",
  "McMaster University",
  "University of Alberta",
  "Université de Montréal",
  "University of Waterloo",
  "University of Ottawa",
  "University of Calgary",
  "Western University",
  "Université Laval",
  "Dalhousie University",
  "Queen’s University",
  "Simon Fraser University",
  "University of Victoria",
  // Canada Additions
  "University of Saskatchewan",
  "Concordia University",
  "Memorial University of Newfoundland",
  "University of Guelph",

  // European Union (selected top universities)
  "ETH Zurich (Switzerland)",
  "University of Amsterdam (Netherlands)",
  "University of Copenhagen (Denmark)",
  "Technical University of Munich (Germany)",
  "Sorbonne University (France)",
  "KU Leuven (Belgium)",
  "University of Helsinki (Finland)",
  // EU Additions
  "Lund University (Sweden)",
  "University of Vienna (Austria)",
  "Heidelberg University (Germany)",
  "Trinity College Dublin (Ireland)",
  "University of Barcelona (Spain)",

  // Australia
  "University of Melbourne",
  "Australian National University",
  "University of Sydney",
  "University of Queensland",
  "Monash University",
  "University of New South Wales",
  "University of Western Australia",
  // Australia Additions
  "University of Adelaide",
  "University of Newcastle",
  "Griffith University",
  "University of Technology Sydney",
  "Curtin University",

  // Asia (top universities)
  "Tsinghua University (China)",
  "Peking University (China)",
  "National University of Singapore",
  "University of Hong Kong",
  "Seoul National University (South Korea)",
  "University of Tokyo (Japan)",
  "Nanyang Technological University (Singapore)",
  // Asia Additions
  "Kyoto University (Japan)",
  "Osaka University (Japan)",
  "Fudan University (China)",
  "Shanghai Jiao Tong University (China)",
  "KAIST (Korea Advanced Institute of Science & Technology)",
  "National Taiwan University (Taiwan)",

  // India
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Science (IISc Bangalore)",
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  // India Additions
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Banaras Hindu University (BHU)",
  "Anna University",
  "University of Calcutta",

  // New Zealand
  "University of Auckland",
  "University of Otago",
  "University of Canterbury",
  "Victoria University of Wellington",
  "Massey University",
  // NZ Additions
  "Lincoln University",
  "Auckland University of Technology",

  // Placeholder for others
  "Other"
]

// Comprehensive mapping of majors to relevant career roles
export const MAJOR_TO_ROLES_MAP: Record<string, string[]> = {
  // Technology & Computer Science
  "Computer Science": [
    "Software Engineer",
    "Data Scientist",
    "Machine Learning Engineer",
    "DevOps Engineer",
    "Full Stack Developer",
    "Backend Developer",
    "Frontend Developer",
    "Mobile App Developer",
    "Cloud Architect",
    "Systems Analyst",
    "Database Administrator",
    "Technical Product Manager"
  ],
  "Software Engineering": [
    "Software Engineer",
    "Full Stack Developer",
    "Backend Developer",
    "Frontend Developer",
    "Mobile App Developer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "QA Engineer",
    "Software Architect",
    "Technical Lead"
  ],
  "Information Technology": [
    "IT Consultant",
    "Systems Administrator",
    "Network Administrator",
    "IT Project Manager",
    "Technical Support Specialist",
    "Database Administrator",
    "IT Security Specialist",
    "Cloud Solutions Architect",
    "IT Manager"
  ],
  "Data Science": [
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "Data Engineer",
    "Business Intelligence Analyst",
    "Quantitative Analyst",
    "Research Scientist",
    "AI Engineer",
    "Data Architect"
  ],
  Cybersecurity: [
    "Cybersecurity Analyst",
    "Security Engineer",
    "Penetration Tester",
    "Security Architect",
    "Information Security Manager",
    "Incident Response Specialist",
    "Security Consultant",
    "Forensic Analyst",
    "Compliance Analyst"
  ],
  "Information Systems": [
    "Systems Analyst",
    "Business Systems Analyst",
    "IT Consultant",
    "Database Administrator",
    "ERP Specialist",
    "Business Intelligence Analyst",
    "Systems Administrator",
    "IT Project Manager",
    "Solutions Architect",
    "Technical Analyst"
  ],
  "Computer Engineering": [
    "Hardware Engineer",
    "Embedded Systems Engineer",
    "Firmware Engineer",
    "ASIC Design Engineer",
    "FPGA Engineer",
    "Systems Engineer",
    "IoT Engineer",
    "Robotics Engineer",
    "Network Engineer",
    "Computer Architect"
  ],
  "Artificial Intelligence": [
    "AI Engineer",
    "Machine Learning Engineer",
    "AI Research Scientist",
    "Natural Language Processing Engineer",
    "Computer Vision Engineer",
    "AI Product Manager",
    "Deep Learning Engineer",
    "AI Ethics Specialist",
    "Robotics Engineer",
    "AI Solutions Architect"
  ],
  "Machine Learning": [
    "Machine Learning Engineer",
    "Data Scientist",
    "ML Research Scientist",
    "MLOps Engineer",
    "Computer Vision Engineer",
    "NLP Engineer",
    "AI Engineer",
    "Deep Learning Engineer",
    "ML Platform Engineer",
    "Predictive Analytics Specialist"
  ],
  "Web Development": [
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Web Designer",
    "JavaScript Developer",
    "PHP Developer",
    "Ruby on Rails Developer",
    "Web Application Developer",
    "E-commerce Developer",
    "WordPress Developer"
  ],
  "Game Development": [
    "Game Developer",
    "Game Designer",
    "Unity Developer",
    "Unreal Engine Developer",
    "Game Programmer",
    "Gameplay Engineer",
    "Graphics Programmer",
    "Game Producer",
    "Level Designer",
    "Technical Game Designer"
  ],

  // Engineering
  "Mechanical Engineering": [
    "Mechanical Engineer",
    "Design Engineer",
    "Manufacturing Engineer",
    "Quality Engineer",
    "Project Engineer",
    "Research & Development Engineer",
    "Automotive Engineer",
    "Aerospace Engineer",
    "HVAC Engineer",
    "Robotics Engineer"
  ],
  "Electrical Engineering": [
    "Electrical Engineer",
    "Electronics Engineer",
    "Power Systems Engineer",
    "Control Systems Engineer",
    "Hardware Engineer",
    "RF Engineer",
    "Embedded Systems Engineer",
    "Telecommunications Engineer",
    "Instrumentation Engineer"
  ],
  "Civil Engineering": [
    "Civil Engineer",
    "Structural Engineer",
    "Transportation Engineer",
    "Environmental Engineer",
    "Construction Manager",
    "Geotechnical Engineer",
    "Water Resources Engineer",
    "Urban Planner",
    "Project Manager"
  ],
  "Chemical Engineering": [
    "Chemical Engineer",
    "Process Engineer",
    "Petroleum Engineer",
    "Materials Engineer",
    "Quality Control Engineer",
    "Environmental Engineer",
    "Pharmaceutical Engineer",
    "Food Process Engineer",
    "Research Engineer",
    "Plant Manager"
  ],
  "Aerospace Engineering": [
    "Aerospace Engineer",
    "Aircraft Design Engineer",
    "Propulsion Engineer",
    "Flight Test Engineer",
    "Systems Engineer",
    "Structural Engineer",
    "Avionics Engineer",
    "Aerodynamics Engineer",
    "Spacecraft Engineer",
    "Mission Planning Engineer"
  ],
  "Biomedical Engineering": [
    "Biomedical Engineer",
    "Medical Device Engineer",
    "Clinical Engineer",
    "Biomaterials Engineer",
    "Tissue Engineer",
    "Rehabilitation Engineer",
    "Regulatory Affairs Specialist",
    "Research Scientist",
    "Quality Engineer",
    "Product Development Engineer"
  ],
  "Industrial Engineering": [
    "Industrial Engineer",
    "Process Improvement Engineer",
    "Quality Engineer",
    "Operations Research Analyst",
    "Supply Chain Engineer",
    "Manufacturing Engineer",
    "Systems Engineer",
    "Lean Six Sigma Specialist",
    "Production Planning Engineer",
    "Ergonomics Engineer"
  ],
  "Environmental Engineering": [
    "Environmental Engineer",
    "Water Resources Engineer",
    "Air Quality Engineer",
    "Sustainability Engineer",
    "Waste Management Engineer",
    "Environmental Consultant",
    "Remediation Engineer",
    "Environmental Compliance Specialist",
    "Green Building Engineer",
    "Climate Change Analyst"
  ],
  "Materials Engineering": [
    "Materials Engineer",
    "Metallurgical Engineer",
    "Polymer Engineer",
    "Ceramics Engineer",
    "Composite Materials Engineer",
    "Failure Analysis Engineer",
    "Quality Control Engineer",
    "Research Scientist",
    "Product Development Engineer",
    "Corrosion Engineer"
  ],
  "Petroleum Engineering": [
    "Petroleum Engineer",
    "Reservoir Engineer",
    "Drilling Engineer",
    "Production Engineer",
    "Completions Engineer",
    "Facilities Engineer",
    "Pipeline Engineer",
    "Energy Analyst",
    "Field Engineer",
    "Project Engineer"
  ],

  // Business & Economics
  "Business Administration": [
    "Business Analyst",
    "Management Consultant",
    "Operations Manager",
    "Business Development Manager",
    "Project Manager",
    "Product Manager",
    "Strategy Analyst",
    "Entrepreneur",
    "General Manager",
    "Account Manager"
  ],
  Finance: [
    "Financial Analyst",
    "Investment Banker",
    "Portfolio Manager",
    "Risk Analyst",
    "Credit Analyst",
    "Financial Planner",
    "Equity Research Analyst",
    "Corporate Finance Analyst",
    "Treasury Analyst",
    "Quantitative Analyst"
  ],
  Marketing: [
    "Marketing Manager",
    "Digital Marketing Specialist",
    "Brand Manager",
    "Content Marketing Manager",
    "Social Media Manager",
    "Marketing Analyst",
    "Product Marketing Manager",
    "SEO Specialist",
    "Marketing Coordinator",
    "Growth Marketing Manager"
  ],
  Economics: [
    "Economic Analyst",
    "Policy Analyst",
    "Market Research Analyst",
    "Financial Analyst",
    "Data Analyst",
    "Consultant",
    "Research Economist",
    "Business Analyst",
    "Risk Analyst",
    "Quantitative Analyst"
  ],
  "Accounting": [
    "Accountant",
    "Auditor",
    "Tax Accountant",
    "Financial Controller",
    "Forensic Accountant",
    "Cost Accountant",
    "Budget Analyst",
    "Financial Examiner",
    "Bookkeeper",
    "Chief Financial Officer"
  ],
  "International Business": [
    "International Business Manager",
    "Export/Import Manager",
    "Global Marketing Manager",
    "International Trade Specialist",
    "Foreign Market Analyst",
    "International Relations Manager",
    "Global Supply Chain Manager",
    "Cross-Cultural Consultant",
    "International Finance Manager",
    "Trade Compliance Specialist"
  ],
  "Entrepreneurship": [
    "Startup Founder",
    "Business Development Manager",
    "Innovation Manager",
    "Venture Capital Analyst",
    "Product Manager",
    "Growth Strategist",
    "Business Consultant",
    "Franchise Owner",
    "Social Entrepreneur",
    "Small Business Owner"
  ],
  "Supply Chain Management": [
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Procurement Manager",
    "Operations Analyst",
    "Inventory Manager",
    "Distribution Manager",
    "Supply Chain Analyst",
    "Warehouse Manager",
    "Transportation Manager",
    "Demand Planner"
  ],
  "Human Resources": [
    "HR Manager",
    "Recruiter",
    "HR Business Partner",
    "Compensation Analyst",
    "Training and Development Manager",
    "Employee Relations Specialist",
    "HR Generalist",
    "Talent Acquisition Specialist",
    "Benefits Administrator",
    "Organizational Development Consultant"
  ],
  "Operations Management": [
    "Operations Manager",
    "Process Improvement Specialist",
    "Quality Assurance Manager",
    "Production Manager",
    "Facilities Manager",
    "Operations Analyst",
    "Supply Chain Manager",
    "Business Process Manager",
    "Lean Six Sigma Specialist",
    "Project Manager"
  ],

  // Science & Mathematics
  "Mathematics": [
    "Data Scientist",
    "Quantitative Analyst",
    "Actuary",
    "Statistician",
    "Operations Research Analyst",
    "Risk Analyst",
    "Financial Analyst",
    "Research Scientist",
    "Math Teacher",
    "Cryptographer"
  ],
  "Statistics": [
    "Statistician",
    "Data Scientist",
    "Biostatistician",
    "Quantitative Analyst",
    "Market Research Analyst",
    "Actuarial Analyst",
    "Business Intelligence Analyst",
    "Research Analyst",
    "Statistical Programmer",
    "Data Analyst"
  ],
  "Physics": [
    "Research Physicist",
    "Data Scientist",
    "Quantitative Analyst",
    "Engineering Physicist",
    "Medical Physicist",
    "Optical Engineer",
    "Aerospace Engineer",
    "Patent Examiner",
    "Science Teacher",
    "Technical Consultant"
  ],
  "Chemistry": [
    "Chemist",
    "Research Scientist",
    "Quality Control Analyst",
    "Pharmaceutical Scientist",
    "Materials Scientist",
    "Forensic Scientist",
    "Environmental Chemist",
    "Chemical Engineer",
    "Lab Manager",
    "Patent Examiner"
  ],
  "Biology": [
    "Research Scientist",
    "Laboratory Technician",
    "Biotechnology Specialist",
    "Environmental Scientist",
    "Microbiologist",
    "Clinical Research Coordinator",
    "Quality Control Analyst",
    "Science Teacher",
    "Conservation Scientist",
    "Pharmaceutical Sales Representative"
  ],
  "Biochemistry": [
    "Biochemist",
    "Research Scientist",
    "Clinical Laboratory Scientist",
    "Pharmaceutical Researcher",
    "Quality Control Analyst",
    "Biotechnology Research Scientist",
    "Forensic Scientist",
    "Medical Scientist",
    "Patent Examiner",
    "Product Development Scientist"
  ],
  "Environmental Science": [
    "Environmental Scientist",
    "Environmental Consultant",
    "Conservation Scientist",
    "Environmental Engineer",
    "Sustainability Specialist",
    "Environmental Policy Analyst",
    "Wildlife Biologist",
    "Environmental Health Specialist",
    "Climate Change Analyst",
    "Environmental Educator"
  ],
  "Geology": [
    "Geologist",
    "Environmental Geologist",
    "Petroleum Geologist",
    "Mining Geologist",
    "Hydrogeologist",
    "Engineering Geologist",
    "Seismologist",
    "Geophysicist",
    "Environmental Consultant",
    "GIS Specialist"
  ],
  "Astronomy": [
    "Astronomer",
    "Research Scientist",
    "Data Scientist",
    "Planetarium Director",
    "Science Writer",
    "Aerospace Engineer",
    "Observatory Technician",
    "Physics Teacher",
    "Software Developer",
    "Satellite Systems Engineer"
  ],
  "Applied Mathematics": [
    "Data Scientist",
    "Quantitative Analyst",
    "Operations Research Analyst",
    "Financial Engineer",
    "Computational Scientist",
    "Algorithm Developer",
    "Machine Learning Engineer",
    "Risk Analyst",
    "Mathematical Modeler",
    "Research Scientist"
  ],

  // Health & Medicine
  "Pre-Medicine": [
    "Medical Scribe",
    "Clinical Research Coordinator",
    "Laboratory Assistant",
    "Medical Assistant",
    "Healthcare Consultant",
    "Pharmaceutical Sales",
    "Public Health Analyst",
    "Medical Writer",
    "Healthcare Administrator",
    "Research Assistant"
  ],
  "Nursing": [
    "Registered Nurse",
    "Nurse Practitioner",
    "Clinical Nurse Specialist",
    "Nurse Manager",
    "Public Health Nurse",
    "Emergency Room Nurse",
    "Pediatric Nurse",
    "Critical Care Nurse",
    "Nurse Educator",
    "Travel Nurse"
  ],
  "Public Health": [
    "Public Health Analyst",
    "Epidemiologist",
    "Health Educator",
    "Community Health Worker",
    "Health Policy Analyst",
    "Environmental Health Specialist",
    "Biostatistician",
    "Health Program Manager",
    "Global Health Specialist",
    "Healthcare Administrator"
  ],
  "Health Administration": [
    "Healthcare Administrator",
    "Hospital Administrator",
    "Medical Practice Manager",
    "Health Services Manager",
    "Healthcare Consultant",
    "Health Information Manager",
    "Patient Services Manager",
    "Healthcare Compliance Officer",
    "Quality Improvement Manager",
    "Healthcare Project Manager"
  ],
  "Pharmacy": [
    "Pharmacist",
    "Clinical Pharmacist",
    "Pharmaceutical Sales Representative",
    "Pharmacy Technician",
    "Pharmaceutical Researcher",
    "Regulatory Affairs Specialist",
    "Drug Safety Specialist",
    "Medical Science Liaison",
    "Pharmacy Manager",
    "Pharmaceutical Quality Analyst"
  ],
  "Physical Therapy": [
    "Physical Therapist",
    "Physical Therapy Assistant",
    "Sports Therapist",
    "Rehabilitation Specialist",
    "Occupational Therapist",
    "Exercise Physiologist",
    "Athletic Trainer",
    "Wellness Coordinator",
    "Clinical Coordinator",
    "Therapy Manager"
  ],
  "Occupational Therapy": [
    "Occupational Therapist",
    "Occupational Therapy Assistant",
    "Rehabilitation Specialist",
    "Ergonomics Specialist",
    "Assistive Technology Specialist",
    "Hand Therapist",
    "Pediatric Therapist",
    "Mental Health Therapist",
    "Vocational Rehabilitation Counselor",
    "Therapy Program Manager"
  ],
  "Nutrition": [
    "Nutritionist",
    "Dietitian",
    "Clinical Nutritionist",
    "Sports Nutritionist",
    "Food Service Manager",
    "Wellness Coach",
    "Public Health Nutritionist",
    "Nutrition Educator",
    "Food Safety Specialist",
    "Nutrition Research Scientist"
  ],
  "Medical Technology": [
    "Medical Laboratory Technologist",
    "Clinical Laboratory Scientist",
    "Medical Equipment Technician",
    "Biomedical Equipment Technician",
    "Laboratory Manager",
    "Quality Control Analyst",
    "Research Technician",
    "Pathology Assistant",
    "Blood Bank Technologist",
    "Diagnostic Medical Sonographer"
  ],
  "Biomedical Sciences": [
    "Biomedical Scientist",
    "Research Scientist",
    "Clinical Research Coordinator",
    "Laboratory Manager",
    "Medical Writer",
    "Biotechnology Researcher",
    "Pharmaceutical Scientist",
    "Toxicologist",
    "Immunologist",
    "Molecular Biologist"
  ],

  // Liberal Arts & Humanities
  "English": [
    "Content Writer",
    "Editor",
    "Technical Writer",
    "Grant Writer",
    "Publishing Assistant",
    "Content Strategist",
    "English Teacher",
    "Literary Agent",
    "Communications Specialist",
    "Proofreader"
  ],
  "Literature": [
    "Editor",
    "Literary Critic",
    "Publishing Assistant",
    "Content Writer",
    "Literary Agent",
    "Book Reviewer",
    "Library Specialist",
    "English Teacher",
    "Editorial Assistant",
    "Creative Writing Instructor"
  ],
  "History": [
    "Museum Curator",
    "Archivist",
    "Research Analyst",
    "History Teacher",
    "Historical Consultant",
    "Cultural Resource Manager",
    "Policy Analyst",
    "Librarian",
    "Documentary Producer",
    "Heritage Manager"
  ],
  "Philosophy": [
    "Ethics Consultant",
    "Policy Analyst",
    "Legal Assistant",
    "Grant Writer",
    "Content Writer",
    "Research Analyst",
    "Philosophy Teacher",
    "Editorial Assistant",
    "Nonprofit Program Manager",
    "Critical Thinking Instructor"
  ],
  "Political Science": [
    "Policy Analyst",
    "Legislative Assistant",
    "Campaign Manager",
    "Political Consultant",
    "Government Affairs Specialist",
    "Intelligence Analyst",
    "Diplomat",
    "Public Affairs Specialist",
    "Lobbyist",
    "International Relations Specialist"
  ],
  "International Relations": [
    "Foreign Service Officer",
    "International Affairs Analyst",
    "Global Policy Advisor",
    "International Development Specialist",
    "Diplomatic Courier",
    "Intelligence Analyst",
    "NGO Program Manager",
    "International Trade Specialist",
    "Cultural Affairs Officer",
    "Peace Corps Volunteer"
  ],
  "Sociology": [
    "Social Researcher",
    "Market Research Analyst",
    "Human Resources Specialist",
    "Community Outreach Coordinator",
    "Social Services Manager",
    "Policy Analyst",
    "Program Coordinator",
    "User Experience Researcher",
    "Diversity and Inclusion Specialist",
    "Urban Planner"
  ],
  "Anthropology": [
    "Anthropologist",
    "Cultural Resource Manager",
    "Museum Curator",
    "User Experience Researcher",
    "Market Research Analyst",
    "International Development Worker",
    "Cultural Consultant",
    "Archaeologist",
    "Social Researcher",
    "Heritage Manager"
  ],
  "Religious Studies": [
    "Religious Educator",
    "Chaplain",
    "Ministry Director",
    "Nonprofit Program Manager",
    "Community Outreach Coordinator",
    "Religious Writer",
    "Interfaith Coordinator",
    "Ethics Consultant",
    "Social Services Coordinator",
    "Youth Program Director"
  ],
  "Foreign Languages": [
    "Translator",
    "Interpreter",
    "Language Teacher",
    "Localization Specialist",
    "International Business Specialist",
    "Foreign Service Officer",
    "Cultural Liaison",
    "Language Program Coordinator",
    "International Relations Specialist",
    "Travel Guide"
  ],

  // Communication & Media
  "Communications": [
    "Public Relations Specialist",
    "Content Writer",
    "Social Media Manager",
    "Communications Manager",
    "Journalist",
    "Marketing Coordinator",
    "Brand Manager",
    "Event Coordinator",
    "Media Planner",
    "Corporate Communications Specialist"
  ],
  "Journalism": [
    "Journalist",
    "News Reporter",
    "Editor",
    "Investigative Journalist",
    "Broadcast Journalist",
    "Digital Content Producer",
    "Photojournalist",
    "News Anchor",
    "Media Analyst",
    "Editorial Writer"
  ],
  "Public Relations": [
    "Public Relations Specialist",
    "PR Manager",
    "Media Relations Coordinator",
    "Communications Director",
    "Press Secretary",
    "Crisis Communications Manager",
    "Brand Ambassador",
    "Event Publicist",
    "Social Media Strategist",
    "Corporate Communications Manager"
  ],
  "Media Studies": [
    "Media Analyst",
    "Content Producer",
    "Media Planner",
    "Digital Content Manager",
    "Social Media Manager",
    "Media Researcher",
    "Production Assistant",
    "Media Consultant",
    "Content Strategist",
    "Multimedia Specialist"
  ],
  "Broadcasting": [
    "Broadcast Producer",
    "Radio Host",
    "TV Producer",
    "News Anchor",
    "Production Manager",
    "Broadcast Engineer",
    "Program Director",
    "Video Editor",
    "Audio Engineer",
    "Studio Manager"
  ],
  "Digital Media": [
    "Digital Content Creator",
    "Social Media Manager",
    "Digital Marketing Specialist",
    "Web Content Manager",
    "UX/UI Designer",
    "Video Producer",
    "Digital Strategist",
    "Content Marketing Manager",
    "SEO Specialist",
    "Digital Project Manager"
  ],
  "Film Studies": [
    "Film Director",
    "Film Producer",
    "Film Editor",
    "Cinematographer",
    "Screenwriter",
    "Film Critic",
    "Production Assistant",
    "Location Manager",
    "Film Archivist",
    "Film Festival Coordinator"
  ],
  "Advertising": [
    "Advertising Manager",
    "Creative Director",
    "Account Executive",
    "Copywriter",
    "Media Buyer",
    "Brand Strategist",
    "Art Director",
    "Digital Marketing Specialist",
    "Campaign Manager",
    "Market Research Analyst"
  ],

  // Creative Arts & Design
  "Graphic Design": [
    "Graphic Designer",
    "UX/UI Designer",
    "Creative Director",
    "Art Director",
    "Web Designer",
    "Brand Designer",
    "Motion Graphics Designer",
    "Product Designer",
    "Visual Designer",
    "Design Manager"
  ],
  "Art": [
    "Artist",
    "Art Director",
    "Gallery Curator",
    "Art Teacher",
    "Museum Educator",
    "Art Therapist",
    "Illustrator",
    "Art Conservator",
    "Art Appraiser",
    "Studio Manager"
  ],
  "Fine Arts": [
    "Fine Artist",
    "Gallery Director",
    "Art Curator",
    "Art Critic",
    "Art Dealer",
    "Museum Director",
    "Art Educator",
    "Exhibition Designer",
    "Art Consultant",
    "Artist Representative"
  ],
  "Interior Design": [
    "Interior Designer",
    "Space Planner",
    "Design Consultant",
    "Furniture Designer",
    "Lighting Designer",
    "Kitchen and Bath Designer",
    "Staging Professional",
    "Color Consultant",
    "Retail Store Designer",
    "Design Project Manager"
  ],
  "Fashion Design": [
    "Fashion Designer",
    "Fashion Merchandiser",
    "Fashion Buyer",
    "Stylist",
    "Pattern Maker",
    "Fashion Illustrator",
    "Textile Designer",
    "Fashion Marketing Manager",
    "Fashion Brand Manager",
    "Fashion Show Producer"
  ],
  "Architecture": [
    "Architect",
    "Urban Designer",
    "Landscape Architect",
    "Interior Designer",
    "Architectural Designer",
    "BIM Specialist",
    "Project Manager",
    "Construction Manager",
    "Sustainability Consultant",
    "Historic Preservationist"
  ],
  "Music": [
    "Musician",
    "Music Producer",
    "Music Teacher",
    "Sound Engineer",
    "Music Director",
    "Composer",
    "Music Therapist",
    "Music Journalist",
    "Music Business Manager",
    "Concert Promoter"
  ],
  "Theater": [
    "Actor",
    "Theater Director",
    "Stage Manager",
    "Theater Producer",
    "Set Designer",
    "Costume Designer",
    "Lighting Designer",
    "Dramaturg",
    "Theater Educator",
    "Casting Director"
  ],
  "Creative Writing": [
    "Author",
    "Copywriter",
    "Content Writer",
    "Screenwriter",
    "Editor",
    "Literary Agent",
    "Grant Writer",
    "Ghostwriter",
    "Writing Coach",
    "Script Doctor"
  ],
  "Photography": [
    "Photographer",
    "Photojournalist",
    "Photo Editor",
    "Studio Manager",
    "Photography Director",
    "Digital Imaging Specialist",
    "Photo Archivist",
    "Photography Teacher",
    "Photo Retoucher",
    "Gallery Curator"
  ],

  // Education
  "Education": [
    "Teacher",
    "Educational Coordinator",
    "Curriculum Developer",
    "Instructional Designer",
    "Educational Consultant",
    "School Administrator",
    "Training Specialist",
    "Academic Advisor",
    "Education Policy Analyst",
    "Learning and Development Manager"
  ],
  "Elementary Education": [
    "Elementary School Teacher",
    "Reading Specialist",
    "Special Education Teacher",
    "Curriculum Coordinator",
    "Educational Assistant",
    "School Counselor",
    "Literacy Coach",
    "After School Program Director",
    "Education Administrator",
    "Child Development Specialist"
  ],
  "Secondary Education": [
    "High School Teacher",
    "Subject Area Specialist",
    "Department Head",
    "Athletic Director",
    "Guidance Counselor",
    "Curriculum Developer",
    "Assistant Principal",
    "Educational Technology Specialist",
    "Career Counselor",
    "Student Activities Coordinator"
  ],
  "Special Education": [
    "Special Education Teacher",
    "Behavior Specialist",
    "Learning Specialist",
    "Resource Teacher",
    "Inclusion Specialist",
    "Speech Therapist",
    "Educational Diagnostician",
    "Assistive Technology Specialist",
    "Transition Coordinator",
    "Special Education Administrator"
  ],
  "Educational Psychology": [
    "Educational Psychologist",
    "School Psychologist",
    "Learning Specialist",
    "Research Analyst",
    "Assessment Specialist",
    "Behavioral Consultant",
    "Educational Researcher",
    "Student Support Specialist",
    "Program Evaluator",
    "Academic Coach"
  ],
  "Educational Psychologist": [
    "Educational Psychologist",
    "School Psychologist",
    "Learning Specialist",
    "Research Analyst",
    "Assessment Specialist",
    "Behavioral Consultant",
    "Educational Researcher",
    "Student Support Specialist",
    "Program Evaluator",
    "Academic Coach"
  ],
  "Curriculum and Instruction": [
    "Curriculum Developer",
    "Instructional Designer",
    "Educational Consultant",
    "Curriculum Coordinator",
    "Training Manager",
    "E-Learning Developer",
    "Educational Technology Specialist",
    "Assessment Specialist",
    "Professional Development Coordinator",
    "Academic Program Manager"
  ],

  // Social Sciences
  "Psychology": [
    "Human Resources Specialist",
    "UX Researcher",
    "Market Research Analyst",
    "Behavioral Analyst",
    "Career Counselor",
    "Case Manager",
    "Research Assistant",
    "Social Services Coordinator",
    "Organizational Development Specialist",
    "Training and Development Specialist"
  ],
  "Criminal Justice": [
    "Police Officer",
    "Detective",
    "Probation Officer",
    "Crime Analyst",
    "Forensic Specialist",
    "Legal Assistant",
    "Corrections Officer",
    "Private Investigator",
    "Security Manager",
    "Criminal Justice Researcher"
  ],
  "Social Work": [
    "Social Worker",
    "Case Manager",
    "Clinical Social Worker",
    "School Social Worker",
    "Healthcare Social Worker",
    "Child Welfare Specialist",
    "Substance Abuse Counselor",
    "Community Outreach Coordinator",
    "Family Services Coordinator",
    "Mental Health Counselor"
  ],
  "Urban Planning": [
    "Urban Planner",
    "City Planner",
    "Transportation Planner",
    "Environmental Planner",
    "Community Development Director",
    "GIS Analyst",
    "Housing Specialist",
    "Zoning Administrator",
    "Economic Development Specialist",
    "Regional Planner"
  ],
  "Geography": [
    "GIS Specialist",
    "Cartographer",
    "Environmental Consultant",
    "Urban Planner",
    "Remote Sensing Analyst",
    "Climate Scientist",
    "Transportation Analyst",
    "Location Analyst",
    "Geography Teacher",
    "Conservation Specialist"
  ],
  "Public Administration": [
    "Public Administrator",
    "City Manager",
    "Policy Analyst",
    "Program Manager",
    "Budget Analyst",
    "Government Relations Specialist",
    "Public Affairs Officer",
    "Grant Manager",
    "Regulatory Compliance Officer",
    "Municipal Clerk"
  ],
  "Law Enforcement": [
    "Police Officer",
    "Detective",
    "Federal Agent",
    "Crime Scene Investigator",
    "Security Manager",
    "Emergency Management Director",
    "Forensic Analyst",
    "Homeland Security Specialist",
    "Intelligence Analyst",
    "Law Enforcement Trainer"
  ],

  // Agriculture & Natural Resources
  "Agriculture": [
    "Agricultural Manager",
    "Farm Manager",
    "Agricultural Inspector",
    "Crop Consultant",
    "Agricultural Sales Representative",
    "Agricultural Extension Agent",
    "Food Scientist",
    "Agricultural Economist",
    "Sustainability Coordinator",
    "Agricultural Research Scientist"
  ],
  "Agricultural Business": [
    "Agricultural Business Manager",
    "Farm Operations Manager",
    "Agricultural Marketing Specialist",
    "Agricultural Loan Officer",
    "Commodity Trader",
    "Agricultural Supply Chain Manager",
    "Food Distribution Manager",
    "Agricultural Policy Analyst",
    "Agribusiness Consultant",
    "Rural Development Specialist"
  ],
  "Forestry": [
    "Forest Ranger",
    "Forestry Technician",
    "Conservation Scientist",
    "Wildlife Manager",
    "Forest Fire Inspector",
    "Urban Forester",
    "Environmental Consultant",
    "Natural Resource Manager",
    "Forest Products Manager",
    "Forestry Research Scientist"
  ],
  "Natural Resources": [
    "Natural Resource Manager",
    "Conservation Officer",
    "Environmental Scientist",
    "Park Ranger",
    "Wildlife Biologist",
    "Resource Economist",
    "Environmental Policy Analyst",
    "Sustainability Coordinator",
    "Land Use Planner",
    "Water Resource Specialist"
  ],
  "Animal Science": [
    "Animal Scientist",
    "Veterinary Technician",
    "Animal Nutritionist",
    "Livestock Manager",
    "Animal Breeder",
    "Zoo Keeper",
    "Animal Behaviorist",
    "Wildlife Rehabilitator",
    "Animal Health Inspector",
    "Research Technician"
  ],
  "Plant Science": [
    "Plant Scientist",
    "Horticulturist",
    "Agronomist",
    "Plant Breeder",
    "Plant Pathologist",
    "Greenhouse Manager",
    "Botanical Garden Director",
    "Agricultural Extension Agent",
    "Plant Research Technician",
    "Seed Analyst"
  ],

  // Other Professional Fields
  "Law": [
    "Attorney",
    "Legal Consultant",
    "Corporate Counsel",
    "Public Defender",
    "Prosecutor",
    "Legal Analyst",
    "Contract Manager",
    "Compliance Officer",
    "Paralegal Supervisor",
    "Legal Writer"
  ],
  "Pre-Law": [
    "Paralegal",
    "Legal Assistant",
    "Law Clerk",
    "Compliance Assistant",
    "Contract Specialist",
    "Legal Secretary",
    "Court Reporter",
    "Legal Researcher",
    "Litigation Support Specialist",
    "Law Firm Administrator"
  ],
  "Library Science": [
    "Librarian",
    "Archivist",
    "Information Specialist",
    "Digital Asset Manager",
    "Research Librarian",
    "Library Director",
    "Cataloging Specialist",
    "Reference Librarian",
    "Library Technology Specialist",
    "Collection Development Manager"
  ],
  "Sports Management": [
    "Sports Marketing Manager",
    "Athletic Director",
    "Sports Agent",
    "Facility Manager",
    "Sports Event Coordinator",
    "Team Operations Manager",
    "Sports Analytics Specialist",
    "Sponsorship Manager",
    "Sports Information Director",
    "Recreation Manager"
  ],
  "Hospitality Management": [
    "Hotel Manager",
    "Restaurant Manager",
    "Event Manager",
    "Food and Beverage Manager",
    "Front Office Manager",
    "Guest Services Manager",
    "Catering Manager",
    "Resort Operations Manager",
    "Revenue Manager",
    "Hospitality Consultant"
  ],
  "Tourism": [
    "Tourism Manager",
    "Travel Agent",
    "Tour Guide",
    "Hotel Manager",
    "Event Coordinator",
    "Destination Marketing Manager",
    "Travel Consultant",
    "Tourism Development Officer",
    "Hospitality Manager",
    "Cruise Director"
  ],
  "Recreation": [
    "Recreation Director",
    "Park Ranger",
    "Recreation Therapist",
    "Community Recreation Coordinator",
    "Sports Facility Manager",
    "Outdoor Recreation Guide",
    "Youth Program Director",
    "Fitness Center Manager",
    "Recreation Program Specialist",
    "Camp Director"
  ],

  // Default roles for unmatched majors
  Other: [
    "Business Analyst",
    "Project Manager",
    "Consultant",
    "Marketing Manager",
    "Sales Representative",
    "Account Manager",
    "Operations Manager",
    "Program Coordinator",
    "Research Analyst",
    "Data Analyst",
    "Human Resources Specialist",
    "Administrative Manager",
    "Customer Success Manager",
    "Product Manager",
    "Financial Analyst",
    "Communications Specialist",
    "Content Creator",
    "Event Coordinator",
    "Training Specialist",
    "Other"
  ],
  Undeclared: [
    "Business Analyst",
    "Project Manager",
    "Consultant",
    "Marketing Manager",
    "Sales Representative",
    "Account Manager",
    "Operations Manager",
    "Program Coordinator",
    "Research Analyst",
    "Data Analyst",
    "Human Resources Specialist",
    "Administrative Manager",
    "Customer Success Manager",
    "Product Manager",
    "Financial Analyst",
    "Communications Specialist",
    "Content Creator",
    "Event Coordinator",
    "Training Specialist",
    "Other"
  ]
}

// Comprehensive list of skills organized by category
export const SKILLS = [
  // Technology & Computer Science
  'JavaScript',
  'Python',
  'Java',
  'React',
  'Node.js',
  'TypeScript',
  'C++',
  'C#',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'PHP',
  'SQL',
  'NoSQL',
  'HTML/CSS',
  'Git',
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Data Analysis',
  'Data Visualization',
  'Big Data',
  'Cybersecurity',
  'Cloud Computing',
  'Mobile Development',
  'Web Development',
  'API Development',
  'Microservices',
  'DevOps',
  'CI/CD',
  'Blockchain',
  'AI/ML',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'R Programming',
  'MATLAB',
  'Unity',
  'Unreal Engine',
  'Game Development',

  // Engineering & Technical
  'CAD/CAM Software',
  'AutoCAD',
  'SolidWorks',
  'CATIA',
  'ANSYS',
  'Circuit Design',
  'PCB Design',
  'Embedded Systems',
  'Arduino',
  'Raspberry Pi',
  'PLC Programming',
  'SCADA Systems',
  'Manufacturing Processes',
  'Quality Control',
  'Six Sigma',
  'Lean Manufacturing',
  'Technical Drawing',
  'Systems Design',
  'Process Optimization',
  'Robotics',
  'Control Systems',
  'Signal Processing',
  'IoT Development',
  'Firmware Development',
  '3D Printing',
  'CNC Programming',
  'Welding',
  'Materials Science',
  'Thermodynamics',
  'Fluid Mechanics',
  'Structural Analysis',

  // Business & Finance
  'Financial Analysis',
  'Financial Modeling',
  'Excel/Spreadsheets',
  'Market Research',
  'Business Strategy',
  'Budgeting',
  'Forecasting',
  'Sales',
  'Customer Service',
  'Negotiation',
  'Business Development',
  'Accounting',
  'Bookkeeping',
  'QuickBooks',
  'SAP',
  'Risk Assessment',
  'Investment Analysis',
  'Portfolio Management',
  'Valuation',
  'M&A Analysis',
  'Corporate Finance',
  'Trading',
  'Bloomberg Terminal',
  'Power BI',
  'Tableau',
  'Business Intelligence',
  'ERP Systems',
  'CRM Software',
  'Salesforce',

  // Marketing & Creative
  'Digital Marketing',
  'Social Media Management',
  'Content Creation',
  'Content Strategy',
  'SEO/SEM',
  'Google Analytics',
  'Adobe Creative Suite',
  'Photoshop',
  'Illustrator',
  'InDesign',
  'Premiere Pro',
  'After Effects',
  'Graphic Design',
  'UI/UX Design',
  'Figma',
  'Sketch',
  'Video Editing',
  'Photography',
  'Copywriting',
  'Brand Management',
  'Email Marketing',
  'Marketing Automation',
  'HubSpot',
  'Mailchimp',
  'Campaign Management',
  'A/B Testing',
  'Conversion Optimization',
  'Influencer Marketing',
  'Affiliate Marketing',

  // Science & Research
  'Laboratory Techniques',
  'PCR',
  'Western Blotting',
  'Cell Culture',
  'Microscopy',
  'Spectroscopy',
  'Chromatography',
  'Statistical Analysis',
  'SPSS',
  'SAS',
  'Research Methodology',
  'Scientific Writing',
  'Data Collection',
  'Experimental Design',
  'Literature Review',
  'Grant Writing',
  'Field Research',
  'Clinical Trials',
  'GLP/GMP',
  'Lab Safety',
  'Bioinformatics',
  'Genomics',
  'Proteomics',

  // Healthcare & Medicine
  'Patient Care',
  'Medical Terminology',
  'Clinical Skills',
  'Healthcare Regulations',
  'HIPAA Compliance',
  'Electronic Health Records',
  'Epic',
  'Cerner',
  'Medical Coding',
  'ICD-10',
  'CPT Coding',
  'First Aid/CPR',
  'BLS Certification',
  'ACLS Certification',
  'Pharmacology',
  'Medication Administration',
  'Vital Signs',
  'Phlebotomy',
  'Medical Imaging',
  'Telemedicine',

  // Communication & Language
  'Public Speaking',
  'Presentation Skills',
  'Technical Writing',
  'Business Writing',
  'Academic Writing',
  'Foreign Languages',
  'Spanish',
  'Mandarin',
  'French',
  'German',
  'Japanese',
  'Arabic',
  'Translation',
  'Interpretation',
  'Active Listening',
  'Interpersonal Skills',
  'Cross-cultural Communication',
  'Nonverbal Communication',
  'Persuasion',
  'Storytelling',

  // Management & Leadership
  'Project Management',
  'Agile/Scrum',
  'PMP Certification',
  'Team Leadership',
  'Strategic Planning',
  'Change Management',
  'Conflict Resolution',
  'Decision Making',
  'Delegation',
  'Performance Management',
  'Coaching',
  'Mentoring',
  'Budget Management',
  'Resource Allocation',
  'Stakeholder Management',
  'Risk Management',
  'Process Improvement',
  'Organizational Development',
  'Succession Planning',

  // Analytical & Problem-Solving
  'Critical Thinking',
  'Problem Solving',
  'Analytical Thinking',
  'Root Cause Analysis',
  'Systems Thinking',
  'Quantitative Analysis',
  'Qualitative Analysis',
  'Research',
  'Hypothesis Testing',
  'Logic',
  'Pattern Recognition',
  'Troubleshooting',
  'Innovation',
  'Design Thinking',

  // Soft Skills
  'Teamwork',
  'Time Management',
  'Adaptability',
  'Creativity',
  'Emotional Intelligence',
  'Work Ethic',
  'Attention to Detail',
  'Organization',
  'Flexibility',
  'Initiative',
  'Self-motivation',
  'Resilience',
  'Cultural Awareness',
  'Ethics',
  'Reliability',
  'Multitasking',
  'Stress Management',
  'Networking',

  // Industry-Specific
  'Supply Chain Management',
  'Logistics',
  'Inventory Management',
  'Procurement',
  'Event Planning',
  'Teaching/Training',
  'Instructional Design',
  'Curriculum Development',
  'Legal Research',
  'Contract Review',
  'Compliance',
  'Policy Analysis',
  'Environmental Assessment',
  'Sustainability',
  'Urban Planning',
  'GIS',
  'Agricultural Practices',
  'Hospitality Management',
  'Tourism',
  'Real Estate',
  'Property Management',
  'Retail Management',
  'E-commerce',
  'Customer Experience',
  'User Research',
  'Market Analysis',
  'Competitive Analysis',
  'Product Development',
  'Quality Assurance',
  'ISO Standards',
  'Auditing',
  'Tax Preparation',
  'Payroll Processing',
  'HR Management',
  'Recruiting',
  'Talent Acquisition',
  'Benefits Administration',
  'Labor Relations',
  'Training & Development',
  'OSHA Compliance',
  'Food Safety',
  'HACCP',
  'Menu Planning',
  'Cost Control',
  'Vendor Management',
  'Contract Negotiation'
]

// Comprehensive mapping of majors to relevant skills
export const MAJOR_TO_SKILLS_MAP: Record<string, string[]> = {
  // Technology & Computer Science
  "Computer Science": [
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "SQL",
    "Git",
    "React",
    "Node.js",
    "Machine Learning",
    "Data Analysis",
    "AWS",
    "Docker",
    "API Development",
    "Web Development",
    "Mobile Development",
    "DevOps",
    "Cloud Computing",
    "Cybersecurity",
    "Problem Solving",
    "Critical Thinking",
    "Team Leadership",
    "Agile/Scrum",
    "Technical Writing",
    "Presentation Skills"
  ],
  "Software Engineering": [
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Git",
    "Docker",
    "Kubernetes",
    "AWS",
    "SQL",
    "NoSQL",
    "API Development",
    "Microservices",
    "Mobile Development",
    "Web Development",
    "Agile/Scrum",
    "CI/CD",
    "DevOps",
    "Problem Solving",
    "Systems Design",
    "Technical Writing",
    "Teamwork",
    "Project Management"
  ],
  "Data Science": [
    "Python",
    "R Programming",
    "SQL",
    "Machine Learning",
    "Deep Learning",
    "Statistical Analysis",
    "Data Analysis",
    "Data Visualization",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Big Data",
    "Natural Language Processing",
    "Computer Vision",
    "A/B Testing",
    "Tableau",
    "Power BI",
    "Business Intelligence",
    "AWS",
    "Problem Solving",
    "Critical Thinking",
    "Presentation Skills",
    "Research",
    "Technical Writing"
  ],
  "Cybersecurity": [
    "Cybersecurity",
    "Python",
    "Linux",
    "Network Security",
    "Cloud Security",
    "AWS",
    "Azure",
    "Penetration Testing",
    "Risk Assessment",
    "Compliance",
    "HIPAA Compliance",
    "Incident Response",
    "Forensics",
    "Firewalls",
    "Encryption",
    "Security Auditing",
    "Ethical Hacking",
    "Problem Solving",
    "Critical Thinking",
    "Technical Writing",
    "Attention to Detail",
    "Analytical Thinking",
    "Team Leadership"
  ],
  "Information Technology": [
    "Python",
    "SQL",
    "Cloud Computing",
    "AWS",
    "Azure",
    "Network Administration",
    "Cybersecurity",
    "Technical Support",
    "Database Management",
    "IT Infrastructure",
    "Windows Server",
    "Linux",
    "Virtualization",
    "Help Desk",
    "Project Management",
    "Customer Service",
    "Problem Solving",
    "Communication Skills",
    "Troubleshooting"
  ],
  "Information Systems": [
    "SQL",
    "Database Management",
    "Business Analysis",
    "ERP Systems",
    "SAP",
    "Salesforce",
    "Data Analysis",
    "Project Management",
    "Systems Analysis",
    "Business Intelligence",
    "Excel/Spreadsheets",
    "Power BI",
    "Process Improvement",
    "Communication Skills",
    "Problem Solving",
    "Technical Writing",
    "Stakeholder Management"
  ],
  "Computer Engineering": [
    "C++",
    "Python",
    "Embedded Systems",
    "Circuit Design",
    "PCB Design",
    "FPGA",
    "Verilog/VHDL",
    "Arduino",
    "Raspberry Pi",
    "IoT Development",
    "Firmware Development",
    "Signal Processing",
    "Control Systems",
    "MATLAB",
    "Assembly Language",
    "Hardware Design",
    "Problem Solving",
    "Technical Documentation"
  ],
  "Artificial Intelligence": [
    "Python",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Natural Language Processing",
    "Computer Vision",
    "AI/ML",
    "Neural Networks",
    "Reinforcement Learning",
    "Data Analysis",
    "Mathematics",
    "Statistics",
    "Research",
    "Problem Solving",
    "Critical Thinking",
    "Innovation",
    "Ethics"
  ],
  "Web Development": [
    "HTML/CSS",
    "JavaScript",
    "React",
    "Node.js",
    "TypeScript",
    "Web Development",
    "UI/UX Design",
    "Responsive Design",
    "Git",
    "API Development",
    "SQL",
    "MongoDB",
    "WordPress",
    "SEO/SEM",
    "Figma",
    "Adobe Creative Suite",
    "Problem Solving",
    "Creativity"
  ],
  "Game Development": [
    "Unity",
    "Unreal Engine",
    "C++",
    "C#",
    "Game Development",
    "3D Modeling",
    "Animation",
    "Physics",
    "AI Programming",
    "Level Design",
    "Scripting",
    "Git",
    "Problem Solving",
    "Creativity",
    "Teamwork",
    "Mathematics",
    "Storytelling"
  ],
  
  // Engineering
  "Mechanical Engineering": [
    "CAD/CAM Software",
    "SolidWorks",
    "AutoCAD",
    "ANSYS",
    "MATLAB",
    "Python",
    "Manufacturing Processes",
    "3D Printing",
    "CNC Programming",
    "Thermodynamics",
    "Fluid Mechanics",
    "Materials Science",
    "Control Systems",
    "Robotics",
    "Quality Control",
    "Six Sigma",
    "Project Management",
    "Technical Drawing",
    "Problem Solving",
    "Team Leadership",
    "Technical Writing"
  ],
  "Electrical Engineering": [
    "Circuit Design",
    "PCB Design",
    "MATLAB",
    "C++",
    "Python",
    "Embedded Systems",
    "Arduino",
    "Signal Processing",
    "Control Systems",
    "PLC Programming",
    "SCADA Systems",
    "Power Systems",
    "Electronics",
    "AutoCAD",
    "Oscilloscopes",
    "Multimeters",
    "Project Management",
    "Problem Solving",
    "Technical Documentation",
    "Quality Control"
  ],
  "Civil Engineering": [
    "AutoCAD",
    "Civil 3D",
    "Structural Analysis",
    "Project Management",
    "Construction Management",
    "Surveying",
    "Building Codes",
    "Environmental Engineering",
    "Transportation Planning",
    "Geotechnical Engineering",
    "Water Resources",
    "MATLAB",
    "Excel/Spreadsheets",
    "Cost Estimation",
    "Quality Control",
    "Safety Management",
    "Problem Solving",
    "Team Leadership",
    "Communication Skills"
  ],
  "Chemical Engineering": [
    "Process Design",
    "MATLAB",
    "Aspen Plus",
    "Chemical Processes",
    "Thermodynamics",
    "Fluid Mechanics",
    "Heat Transfer",
    "Mass Transfer",
    "Process Control",
    "Safety Management",
    "Quality Control",
    "Six Sigma",
    "Project Management",
    "Laboratory Techniques",
    "Environmental Compliance",
    "Problem Solving",
    "Technical Writing",
    "Data Analysis"
  ],
  "Aerospace Engineering": [
    "MATLAB",
    "CATIA",
    "ANSYS",
    "Aerodynamics",
    "Propulsion",
    "Flight Mechanics",
    "Structural Analysis",
    "Control Systems",
    "CAD/CAM Software",
    "Systems Engineering",
    "Project Management",
    "Technical Documentation",
    "Problem Solving",
    "Team Leadership",
    "Quality Control",
    "Research",
    "Critical Thinking"
  ],
  "Biomedical Engineering": [
    "MATLAB",
    "Python",
    "CAD/CAM Software",
    "Medical Device Design",
    "Biomaterials",
    "Tissue Engineering",
    "Medical Imaging",
    "Signal Processing",
    "Laboratory Techniques",
    "FDA Regulations",
    "Clinical Trials",
    "Quality Control",
    "Project Management",
    "Research",
    "Problem Solving",
    "Technical Writing",
    "Team Collaboration"
  ],
  "Industrial Engineering": [
    "Process Optimization",
    "Six Sigma",
    "Lean Manufacturing",
    "Quality Control",
    "Supply Chain Management",
    "Operations Research",
    "Statistical Analysis",
    "Excel/Spreadsheets",
    "Project Management",
    "Simulation Software",
    "ERP Systems",
    "Data Analysis",
    "Cost Analysis",
    "Problem Solving",
    "Team Leadership",
    "Communication Skills"
  ],
  "Environmental Engineering": [
    "Environmental Assessment",
    "Water Treatment",
    "Air Quality",
    "Waste Management",
    "Sustainability",
    "GIS",
    "AutoCAD",
    "Environmental Regulations",
    "Laboratory Techniques",
    "Data Analysis",
    "Project Management",
    "Technical Writing",
    "Field Research",
    "Problem Solving",
    "Communication Skills",
    "Team Collaboration"
  ],
  
  // Business & Economics
  "Business Administration": [
    "Business Strategy",
    "Project Management",
    "Financial Analysis",
    "Market Research",
    "Excel/Spreadsheets",
    "PowerPoint",
    "Data Analysis",
    "Leadership",
    "Team Leadership",
    "Strategic Planning",
    "Operations Management",
    "Business Development",
    "Salesforce",
    "Communication Skills",
    "Presentation Skills",
    "Negotiation",
    "Problem Solving",
    "Critical Thinking",
    "Stakeholder Management",
    "Decision Making"
  ],
  "Finance": [
    "Financial Analysis",
    "Financial Modeling",
    "Excel/Spreadsheets",
    "Bloomberg Terminal",
    "Python",
    "R Programming",
    "SQL",
    "Valuation",
    "Investment Analysis",
    "Portfolio Management",
    "Risk Assessment",
    "Corporate Finance",
    "M&A Analysis",
    "Trading",
    "Accounting",
    "Statistical Analysis",
    "Data Analysis",
    "PowerPoint",
    "Problem Solving",
    "Attention to Detail",
    "Critical Thinking",
    "Communication Skills"
  ],
  "Marketing": [
    "Digital Marketing",
    "Social Media Management",
    "Content Creation",
    "SEO/SEM",
    "Google Analytics",
    "Marketing Automation",
    "HubSpot",
    "Mailchimp",
    "Adobe Creative Suite",
    "Photoshop",
    "Brand Management",
    "Market Research",
    "Copywriting",
    "Email Marketing",
    "Campaign Management",
    "A/B Testing",
    "Data Analysis",
    "Excel/Spreadsheets",
    "Presentation Skills",
    "Creativity",
    "Communication Skills",
    "Project Management",
    "Influencer Marketing"
  ],
  "Economics": [
    "Statistical Analysis",
    "Data Analysis",
    "Excel/Spreadsheets",
    "R Programming",
    "Python",
    "STATA",
    "Econometrics",
    "Financial Analysis",
    "Market Research",
    "Policy Analysis",
    "Research",
    "Critical Thinking",
    "Problem Solving",
    "Mathematical Modeling",
    "Presentation Skills",
    "Technical Writing",
    "Quantitative Analysis"
  ],
  "Accounting": [
    "Accounting",
    "Financial Analysis",
    "Excel/Spreadsheets",
    "QuickBooks",
    "Tax Preparation",
    "Auditing",
    "Financial Reporting",
    "Bookkeeping",
    "SAP",
    "Cost Accounting",
    "Compliance",
    "Attention to Detail",
    "Problem Solving",
    "Critical Thinking",
    "Organization",
    "Time Management",
    "Ethics"
  ],
  "International Business": [
    "Foreign Languages",
    "Cross-cultural Communication",
    "International Trade",
    "Global Marketing",
    "Supply Chain Management",
    "Market Research",
    "Business Strategy",
    "Excel/Spreadsheets",
    "Project Management",
    "Negotiation",
    "Cultural Awareness",
    "Communication Skills",
    "Adaptability",
    "Problem Solving",
    "Leadership"
  ],
  "Supply Chain Management": [
    "Supply Chain Management",
    "Logistics",
    "Inventory Management",
    "Procurement",
    "ERP Systems",
    "SAP",
    "Excel/Spreadsheets",
    "Data Analysis",
    "Operations Management",
    "Project Management",
    "Vendor Management",
    "Cost Control",
    "Problem Solving",
    "Negotiation",
    "Communication Skills",
    "Analytical Thinking"
  ],
  "Human Resources": [
    "HR Management",
    "Recruiting",
    "Talent Acquisition",
    "Employee Relations",
    "Benefits Administration",
    "HRIS Systems",
    "Excel/Spreadsheets",
    "Communication Skills",
    "Conflict Resolution",
    "Training & Development",
    "Performance Management",
    "Labor Relations",
    "Compliance",
    "Emotional Intelligence",
    "Problem Solving",
    "Organization"
  ],
  
  // Science & Mathematics
  "Mathematics": [
    "Mathematical Modeling",
    "Statistical Analysis",
    "Python",
    "R Programming",
    "MATLAB",
    "Data Analysis",
    "Calculus",
    "Linear Algebra",
    "Problem Solving",
    "Critical Thinking",
    "Research",
    "LaTeX",
    "Quantitative Analysis",
    "Logic",
    "Abstract Thinking",
    "Technical Writing",
    "Teaching/Training"
  ],
  "Statistics": [
    "Statistical Analysis",
    "R Programming",
    "Python",
    "SAS",
    "SPSS",
    "Data Analysis",
    "Data Visualization",
    "Machine Learning",
    "A/B Testing",
    "Hypothesis Testing",
    "Excel/Spreadsheets",
    "SQL",
    "Tableau",
    "Research",
    "Problem Solving",
    "Critical Thinking",
    "Technical Writing"
  ],
  "Biology": [
    "Laboratory Techniques",
    "PCR",
    "Cell Culture",
    "Microscopy",
    "Research Methodology",
    "Scientific Writing",
    "Data Analysis",
    "Statistical Analysis",
    "R Programming",
    "Python",
    "Experimental Design",
    "Field Research",
    "Lab Safety",
    "Problem Solving",
    "Critical Thinking",
    "Attention to Detail",
    "Technical Documentation",
    "Presentation Skills"
  ],
  "Chemistry": [
    "Laboratory Techniques",
    "Spectroscopy",
    "Chromatography",
    "Titration",
    "Chemical Analysis",
    "Lab Safety",
    "GLP/GMP",
    "Research Methodology",
    "Scientific Writing",
    "Data Analysis",
    "Statistical Analysis",
    "Quality Control",
    "MATLAB",
    "Excel/Spreadsheets",
    "Problem Solving",
    "Critical Thinking",
    "Attention to Detail",
    "Technical Documentation"
  ],
  "Physics": [
    "Python",
    "MATLAB",
    "Mathematical Modeling",
    "Data Analysis",
    "Statistical Analysis",
    "Laboratory Techniques",
    "Research Methodology",
    "Scientific Writing",
    "LaTeX",
    "Computational Physics",
    "Electronics",
    "Optics",
    "Problem Solving",
    "Critical Thinking",
    "Analytical Thinking",
    "Technical Documentation",
    "Presentation Skills"
  ],
  "Biochemistry": [
    "Laboratory Techniques",
    "PCR",
    "Western Blotting",
    "Protein Purification",
    "Chromatography",
    "Spectroscopy",
    "Cell Culture",
    "Research Methodology",
    "Scientific Writing",
    "Data Analysis",
    "Statistical Analysis",
    "Lab Safety",
    "GLP/GMP",
    "Problem Solving",
    "Critical Thinking",
    "Attention to Detail"
  ],
  "Environmental Science": [
    "Environmental Assessment",
    "GIS",
    "Field Research",
    "Data Analysis",
    "Statistical Analysis",
    "Laboratory Techniques",
    "Sustainability",
    "Environmental Regulations",
    "Research Methodology",
    "Scientific Writing",
    "Excel/Spreadsheets",
    "R Programming",
    "Problem Solving",
    "Critical Thinking",
    "Communication Skills",
    "Project Management"
  ],
  
  // Health & Medicine
  "Pre-Medicine": [
    "Laboratory Techniques",
    "Research Methodology",
    "Scientific Writing",
    "Medical Terminology",
    "Biology",
    "Chemistry",
    "Data Analysis",
    "Clinical Research",
    "Patient Care",
    "Communication Skills",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Leadership",
    "Volunteer Experience",
    "Empathy"
  ],
  "Nursing": [
    "Patient Care",
    "Clinical Skills",
    "Medical Terminology",
    "Electronic Health Records",
    "Epic",
    "Medication Administration",
    "Vital Signs",
    "First Aid/CPR",
    "BLS Certification",
    "Communication Skills",
    "Emotional Intelligence",
    "Time Management",
    "Critical Thinking",
    "Problem Solving",
    "Team Leadership",
    "Compassion",
    "Attention to Detail"
  ],
  "Public Health": [
    "Epidemiology",
    "Statistical Analysis",
    "Data Analysis",
    "Research Methodology",
    "Health Policy",
    "Community Outreach",
    "Program Management",
    "Grant Writing",
    "SPSS",
    "R Programming",
    "GIS",
    "Communication Skills",
    "Presentation Skills",
    "Problem Solving",
    "Cultural Awareness",
    "Project Management"
  ],
  "Pharmacy": [
    "Pharmacology",
    "Medical Terminology",
    "Drug Interactions",
    "Patient Care",
    "Healthcare Regulations",
    "Medication Management",
    "Clinical Skills",
    "Communication Skills",
    "Attention to Detail",
    "Problem Solving",
    "Critical Thinking",
    "Customer Service",
    "Time Management",
    "Ethics"
  ],
  
  // Liberal Arts & Humanities
  "Psychology": [
    "Research Methodology",
    "Statistical Analysis",
    "SPSS",
    "Data Analysis",
    "Scientific Writing",
    "Qualitative Research",
    "Quantitative Research",
    "Communication Skills",
    "Active Listening",
    "Emotional Intelligence",
    "Critical Thinking",
    "Problem Solving",
    "Empathy",
    "Observation",
    "Ethics",
    "Presentation Skills"
  ],
  "English": [
    "Technical Writing",
    "Creative Writing",
    "Editing",
    "Proofreading",
    "Research",
    "Critical Thinking",
    "Communication Skills",
    "Content Creation",
    "Copywriting",
    "Public Speaking",
    "Teaching/Training",
    "Grammar",
    "Literature Analysis",
    "MLA/APA Citation",
    "Problem Solving",
    "Time Management",
    "Creativity"
  ],
  "History": [
    "Research",
    "Archival Research",
    "Critical Thinking",
    "Analytical Thinking",
    "Writing",
    "Communication Skills",
    "Data Analysis",
    "Primary Source Analysis",
    "Teaching/Training",
    "Public Speaking",
    "Problem Solving",
    "Time Management",
    "Attention to Detail",
    "Cultural Awareness"
  ],
  "Political Science": [
    "Policy Analysis",
    "Research",
    "Data Analysis",
    "Statistical Analysis",
    "Critical Thinking",
    "Writing",
    "Communication Skills",
    "Public Speaking",
    "Debate",
    "International Relations",
    "Government",
    "Law",
    "Problem Solving",
    "Analytical Thinking",
    "Negotiation"
  ],
  "Sociology": [
    "Research Methodology",
    "Statistical Analysis",
    "SPSS",
    "Data Analysis",
    "Qualitative Research",
    "Quantitative Research",
    "Survey Design",
    "Critical Thinking",
    "Communication Skills",
    "Cultural Awareness",
    "Problem Solving",
    "Writing",
    "Observation",
    "Empathy"
  ],
  
  // Communication & Media
  "Communications": [
    "Communication Skills",
    "Public Relations",
    "Social Media Management",
    "Content Creation",
    "Writing",
    "Digital Marketing",
    "Adobe Creative Suite",
    "Video Editing",
    "Photography",
    "Public Speaking",
    "Event Planning",
    "Brand Management",
    "Crisis Communication",
    "Media Relations",
    "Creativity",
    "Project Management"
  ],
  "Journalism": [
    "Writing",
    "Investigative Research",
    "Interviewing",
    "AP Style",
    "Photography",
    "Video Editing",
    "Social Media Management",
    "Digital Media",
    "Fact-checking",
    "Deadline Management",
    "Communication Skills",
    "Critical Thinking",
    "Ethics",
    "Adaptability",
    "Networking"
  ],
  "Media Studies": [
    "Media Analysis",
    "Content Creation",
    "Video Editing",
    "Adobe Creative Suite",
    "Social Media Management",
    "Digital Marketing",
    "Research",
    "Critical Thinking",
    "Communication Skills",
    "Storytelling",
    "Project Management",
    "Creativity",
    "Cultural Awareness"
  ],
  
  // Creative Arts & Design
  "Graphic Design": [
    "Adobe Creative Suite",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "Figma",
    "Sketch",
    "UI/UX Design",
    "Typography",
    "Brand Management",
    "Web Design",
    "Print Design",
    "Color Theory",
    "Layout Design",
    "Creativity",
    "Communication Skills",
    "Project Management",
    "Time Management",
    "Attention to Detail",
    "Problem Solving",
    "Portfolio Development"
  ],
  "Architecture": [
    "AutoCAD",
    "Revit",
    "SketchUp",
    "3D Modeling",
    "Rhino",
    "Adobe Creative Suite",
    "Technical Drawing",
    "Building Codes",
    "Sustainability",
    "Project Management",
    "Design Thinking",
    "Structural Design",
    "Environmental Design",
    "Communication Skills",
    "Presentation Skills",
    "Problem Solving",
    "Creativity",
    "Critical Thinking",
    "Team Leadership",
    "Attention to Detail"
  ],
  "Fine Arts": [
    "Drawing",
    "Painting",
    "Sculpture",
    "Art History",
    "Adobe Creative Suite",
    "Photography",
    "Digital Art",
    "Creativity",
    "Critical Thinking",
    "Visual Communication",
    "Portfolio Development",
    "Exhibition Planning",
    "Art Critique",
    "Time Management",
    "Self-motivation"
  ],
  "Interior Design": [
    "AutoCAD",
    "SketchUp",
    "3D Modeling",
    "Space Planning",
    "Color Theory",
    "Materials Knowledge",
    "Lighting Design",
    "Adobe Creative Suite",
    "Project Management",
    "Client Relations",
    "Budgeting",
    "Creativity",
    "Communication Skills",
    "Problem Solving",
    "Attention to Detail"
  ],
  "Fashion Design": [
    "Fashion Illustration",
    "Pattern Making",
    "Sewing",
    "Adobe Creative Suite",
    "Textile Knowledge",
    "Trend Forecasting",
    "Fashion History",
    "Merchandising",
    "Brand Management",
    "Creativity",
    "Attention to Detail",
    "Time Management",
    "Communication Skills",
    "Business Acumen"
  ],
  "Photography": [
    "Photography",
    "Adobe Lightroom",
    "Photoshop",
    "Studio Lighting",
    "Photo Editing",
    "Composition",
    "Digital Imaging",
    "Video Production",
    "Client Relations",
    "Marketing",
    "Creativity",
    "Attention to Detail",
    "Time Management",
    "Business Skills"
  ],
  "Music": [
    "Music Theory",
    "Performance",
    "Music Production",
    "Audio Engineering",
    "Pro Tools",
    "Logic Pro",
    "Ableton Live",
    "Teaching/Training",
    "Collaboration",
    "Creativity",
    "Discipline",
    "Time Management",
    "Networking",
    "Stage Presence"
  ],
  
  // Education
  "Education": [
    "Teaching/Training",
    "Curriculum Development",
    "Classroom Management",
    "Lesson Planning",
    "Educational Technology",
    "Assessment Design",
    "Communication Skills",
    "Patience",
    "Creativity",
    "Leadership",
    "Organization",
    "Time Management",
    "Adaptability",
    "Empathy",
    "Public Speaking"
  ],
  "Elementary Education": [
    "Teaching/Training",
    "Child Development",
    "Classroom Management",
    "Lesson Planning",
    "Differentiated Instruction",
    "Educational Technology",
    "Reading Instruction",
    "Math Instruction",
    "Communication Skills",
    "Patience",
    "Creativity",
    "Organization",
    "Empathy",
    "Flexibility"
  ],
  "Educational Psychology": [
    "Psychological Assessment",
    "Learning Theory",
    "Child Development",
    "Behavioral Analysis",
    "Research Methodology",
    "Statistical Analysis",
    "SPSS",
    "Counseling",
    "Special Education",
    "Cognitive Development",
    "Educational Testing",
    "Intervention Planning",
    "Communication Skills",
    "Empathy",
    "Active Listening",
    "Problem Solving",
    "Critical Thinking",
    "Report Writing",
    "Ethics",
    "Cultural Awareness"
  ],
  "Educational Psychologist": [
    "Psychological Assessment",
    "Learning Theory",
    "Child Development",
    "Behavioral Analysis",
    "Research Methodology",
    "Statistical Analysis",
    "SPSS",
    "Counseling",
    "Special Education",
    "Cognitive Development",
    "Educational Testing",
    "Intervention Planning",
    "Communication Skills",
    "Empathy",
    "Active Listening",
    "Problem Solving",
    "Critical Thinking",
    "Report Writing",
    "Ethics",
    "Cultural Awareness"
  ],
  
  // Social Sciences
  "Criminal Justice": [
    "Law Enforcement",
    "Criminal Law",
    "Investigation",
    "Report Writing",
    "Critical Thinking",
    "Ethics",
    "Communication Skills",
    "Problem Solving",
    "Attention to Detail",
    "Physical Fitness",
    "Conflict Resolution",
    "Decision Making",
    "Integrity",
    "Teamwork"
  ],
  "Social Work": [
    "Case Management",
    "Counseling",
    "Crisis Intervention",
    "Community Outreach",
    "Advocacy",
    "Communication Skills",
    "Empathy",
    "Active Listening",
    "Problem Solving",
    "Cultural Awareness",
    "Ethics",
    "Organization",
    "Time Management",
    "Resilience"
  ],
  "Urban Planning": [
    "GIS",
    "AutoCAD",
    "Urban Design",
    "Zoning Laws",
    "Environmental Planning",
    "Transportation Planning",
    "Community Engagement",
    "Data Analysis",
    "Project Management",
    "Policy Analysis",
    "Communication Skills",
    "Problem Solving",
    "Critical Thinking",
    "Sustainability"
  ],
  "Geography": [
    "GIS",
    "Remote Sensing",
    "Cartography",
    "Spatial Analysis",
    "Environmental Assessment",
    "Field Research",
    "Data Analysis",
    "Excel/Spreadsheets",
    "Research",
    "Critical Thinking",
    "Problem Solving",
    "Communication Skills",
    "Attention to Detail"
  ],
  
  // Other Professional Fields
  "Law": [
    "Legal Research",
    "Legal Writing",
    "Contract Review",
    "Litigation",
    "Negotiation",
    "Critical Thinking",
    "Analytical Thinking",
    "Communication Skills",
    "Public Speaking",
    "Attention to Detail",
    "Time Management",
    "Ethics",
    "Problem Solving",
    "Persuasion"
  ],
  "Pre-Law": [
    "Legal Research",
    "Writing",
    "Critical Thinking",
    "Analytical Thinking",
    "Public Speaking",
    "Debate",
    "Research",
    "Communication Skills",
    "Time Management",
    "Organization",
    "Attention to Detail",
    "Ethics",
    "Problem Solving"
  ],
  "Sports Management": [
    "Sports Marketing",
    "Event Planning",
    "Facility Management",
    "Sports Analytics",
    "Sponsorship",
    "Public Relations",
    "Budget Management",
    "Communication Skills",
    "Leadership",
    "Negotiation",
    "Project Management",
    "Networking",
    "Problem Solving",
    "Teamwork"
  ],
  "Hospitality Management": [
    "Customer Service",
    "Hotel Operations",
    "Food & Beverage",
    "Event Planning",
    "Revenue Management",
    "Guest Relations",
    "Communication Skills",
    "Leadership",
    "Problem Solving",
    "Multitasking",
    "Cultural Awareness",
    "Time Management",
    "Attention to Detail",
    "Flexibility"
  ],
  
  // Agriculture & Natural Resources
  "Agriculture": [
    "Agricultural Practices",
    "Crop Science",
    "Soil Science",
    "Farm Management",
    "Agricultural Technology",
    "Sustainability",
    "Equipment Operation",
    "Data Analysis",
    "Problem Solving",
    "Physical Stamina",
    "Business Skills",
    "Environmental Awareness",
    "Time Management"
  ],
  
  // Default skills for unmatched majors
  "Other": [
    "Communication Skills",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Time Management",
    "Leadership",
    "Data Analysis",
    "Project Management",
    "Writing",
    "Adaptability",
    "Creativity",
    "Research",
    "Organization",
    "Decision Making",
    "Work Ethic"
  ],
  "Undeclared": [
    "Communication Skills",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Time Management",
    "Leadership",
    "Data Analysis",
    "Project Management",
    "Writing",
    "Adaptability",
    "Creativity",
    "Research",
    "Organization",
    "Decision Making",
    "Work Ethic"
  ]
}

// Helper function to get roles for a major
export function getRolesForMajor(major: string): string[] {
  console.log("getRolesForMajor called with:", major) // Debug log
  
  // First try exact match
  if (MAJOR_TO_ROLES_MAP[major]) {
    console.log("Exact match found for:", major) // Debug log
    return [...MAJOR_TO_ROLES_MAP[major], "Other"]
  }

  // Try to find partial matches
  const majorLower = major.toLowerCase()
  for (const [key, roles] of Object.entries(MAJOR_TO_ROLES_MAP)) {
    if (
      majorLower.includes(key.toLowerCase()) ||
      key.toLowerCase().includes(majorLower)
    ) {
      console.log("Partial match found:", key, "for input:", major) // Debug log
      return [...roles, "Other"]
    }
  }

  // Default to all roles if no match found
  console.log("No match found for:", major, "- using default roles") // Debug log
  return MAJOR_TO_ROLES_MAP["Other"]
}

// Helper function to get skills for a major
export function getSkillsForMajor(major: string): string[] {
  // First try exact match
  if (MAJOR_TO_SKILLS_MAP[major]) {
    return MAJOR_TO_SKILLS_MAP[major]
  }

  // Try to find partial matches
  const majorLower = major.toLowerCase()
  for (const [key, skills] of Object.entries(MAJOR_TO_SKILLS_MAP)) {
    if (
      majorLower.includes(key.toLowerCase()) ||
      key.toLowerCase().includes(majorLower)
    ) {
      return skills
    }
  }

  // Default to generic skills if no match found
  return MAJOR_TO_SKILLS_MAP["Other"]
}
